### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by baditaflorin** [livingbio/syntaxnet_wrapper#14]
pip install git+ssh://git@github.com/livingbio/syntaxnet_wrapper.git#egg=syntaxnet_wrapper
Collecting syntaxnet_wrapper from git+ssh://git@github.com/livingbio/syntaxnet_wrapper.git#egg=syntaxnet_wrapper
  Cloning ssh://git@github.com/livingbio/syntaxnet_wrapper.git to /tmp/pip-build-lXMCyv/syntaxnet-wrapper
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Command "git clone -q ssh://git@github.com/livingbio/syntaxnet_wrapper.git /tmp/pip-build-lXMCyv/syntaxnet-wrapper" failed with error code 128 in None
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
florin@florin-MachineLearning:~$

**Comment by banyh** [comment]
Please use `pip install git+https://github.com/livingbio/syntaxnet_wrapper.git` instead, since you don't have a private key.

**Comment by banyh** [comment]
If you want to put it in a requirement file, use
`-e git+https://github.com/livingbio/syntaxnet_wrapper.git#egg=syntaxnet_wrapper`.
