### ISSUE TITLE
ImportError:No module named syntaxnet

### ISSUE THREAD

**Issue by paulx3** [livingbio/syntaxnet_wrapper#8]
ImportError:No module named syntaxnet
but I don't know how to install syntaxnet package.

**Comment by banyh** [comment]
Did you solve your problem?
Have you ever tried `pip install git+https://github.com/livingbio/syntaxnet_wrapper`?

**Comment by paulx3** [comment]
I solved my problem by cloning the repository and installing it on my server. Thank you
